<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>SIL.Harmony.Tests</RootNamespace>
        <OutputType>Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="GitHubActionsTestLogger" />
        <PackageReference Include="JetBrains.Profiler.SelfApi" />
        <PackageReference Include="Verify.DiffPlex" />
        <PackageReference Include="Verify.EntityFramework" />
        <PackageReference Include="Verify.XunitV3" />
        <PackageReference Include="xunit.v3.mtp-v2" />
        <PackageReference Include="System.Linq.Async"/>
        <PackageReference Include="linq2db" />
        <PackageReference Include="linq2db.Extensions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SIL.Harmony.Sample\SIL.Harmony.Sample.csproj" />
      <ProjectReference Include="..\SIL.Harmony\SIL.Harmony.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="SIL.Harmony.Core"/>
    </ItemGroup>

</Project>
