name: Tests
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
permissions: 
  pull-requests: write #allow benchmark-action to comment on PRs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4

      - name: Build & test
        run: dotnet test --configuration Release --logger GitHubActions
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Continuous Benchmark
        uses: benchmark-action/github-action-benchmark@v1.20.4
        with: 
          tool: benchmarkdotnet
          output-file-path: src\artifacts\bin\SIL.Harmony.Tests\release\BenchmarkDotNet.Artifacts\results\SIL.Harmony.Tests.DataModelPerformanceBenchmarks-report-full-compressed.json
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          summary-always: true
          comment-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          